// Generated by CoffeeScript 1.8.0
(function() {
  var API, Mapping, SchemaManager;

  SchemaManager = require("./schema_manager");

  module.exports = API = (function() {
    function API(_arg) {
      var definition, mapping, mappings, name, _ref;
      this.service_url = _arg.service_url, mappings = _arg.mappings, this.resources = _arg.resources, this.schemas = _arg.schemas;
      if (!(mappings && this.resources && this.schemas)) {
        throw new Error("API specification must provide mappings, resources, and schemas");
      }
      this.mappings = {};
      for (name in mappings) {
        mapping = mappings[name];
        this.mappings[name] = new Mapping(this, mapping);
      }
      _ref = this.resources;
      for (name in _ref) {
        definition = _ref[name];
        definition.name = name;
      }
      this.schema_manager = (function(func, args, ctor) {
        ctor.prototype = func.prototype;
        var child = new ctor, result = func.apply(child, args);
        return Object(result) === result ? result : child;
      })(SchemaManager, this.schemas, function(){});
    }

    API.prototype.decorate = function(context, schema, data) {
      var constructor, mapping, name, _data, _ref;
      if ((name = (_ref = schema.id) != null ? _ref.split("#")[1] : void 0) != null) {
        if ((mapping = this.mappings[name]) != null) {
          constructor = mapping.constructor;
          _data = data;
          if (mapping.query != null) {
            data = function(params) {
              if (_data.url != null) {
                params.url = _data.url;
              }
              return new constructor(context, {
                url: mapping.generate_url(params)
              });
            };
          } else {
            data = new constructor(context, _data);
          }
        }
      }
      return this._decorate(context, schema, data) || data;
    };

    API.prototype._decorate = function(context, schema, data) {
      var addprop, i, item, key, ref, result, value, _i, _len, _ref, _ref1, _results;
      if ((schema == null) || (data == null)) {
        return;
      }
      if (ref = schema.$ref) {
        if ((schema = this.schema_manager.find(ref)) != null) {
          return this.decorate(context, schema, data);
        } else {
          console.error("Can't find ref:", ref);
          return data;
        }
      } else {
        if (schema.type === "array") {
          if (schema.items != null) {
            _results = [];
            for (i = _i = 0, _len = data.length; _i < _len; i = ++_i) {
              item = data[i];
              if ((result = this.decorate(context, schema.items, item)) != null) {
                _results.push(data[i] = result);
              } else {
                _results.push(void 0);
              }
            }
            return _results;
          }
        } else {
          switch (schema.type) {
            case "string":
            case "number":
            case "integer":
            case "boolean":
              return null;
            default:
              _ref = schema.properties;
              for (key in _ref) {
                value = _ref[key];
                if ((result = this.decorate(context, value, data[key])) != null) {
                  data[key] = result;
                }
              }
              if (addprop = schema.additionalProperties) {
                for (key in data) {
                  value = data[key];
                  if (!((_ref1 = schema.properties) != null ? _ref1[key] : void 0)) {
                    data[key] = this.decorate(context, addprop, value);
                  }
                }
              }
              return data;
          }
        }
      }
    };

    return API;

  })();

  API.Mapping = Mapping = (function() {
    function Mapping(api, _arg) {
      var resource;
      this.name = _arg.name, this.resource = _arg.resource, this.url = _arg.url, this.template = _arg.template, this.path = _arg.path, this.query = _arg.query;
      this.service_url = api.service_url;
      if (this.resource == null) {
        this.resource = this.name;
      }
      if (!((this.url != null) || (this.path != null) || (this.template != null))) {
        throw new Error("Mapping is missing any form of URL specification");
      }
      if ((resource = api.resources[this.resource]) == null) {
        throw new Error("Mapping specifies a resource that is not defined");
      }
      this.resource = resource;
    }

    Mapping.prototype.generate_url = function(params) {
      var key, keys, out, part, parts, path, query, query_string, schema, string, template, url, _i, _j, _len, _len1;
      if (params == null) {
        params = {};
      }
      url = this.service_url;
      path = "";
      if (params.constructor === String) {
        url = params;
      } else if (params.url) {
        url = params.url;
      } else if (this.url != null) {
        url = this.url;
      } else if ((template = this.template) != null) {
        parts = template.split("/");
        out = [];
        for (_i = 0, _len = parts.length; _i < _len; _i++) {
          part = parts[_i];
          if (part.indexOf(":") === 0) {
            key = part.slice(1);
            if ((string = params[key]) != null) {
              out.push(string);
            } else {
              throw new Error("Missing key: '" + key + "' in params: " + (JSON.stringify(params)));
            }
          } else {
            out.push(part);
          }
        }
        url = url + out.join("/");
      } else if (this.path != null) {
        path = this.path;
      } else {
        throw new Error("Unusable URL mapping.  Must have url, path, or template field.\nMapping: " + (JSON.stringify(this, null, 2)));
      }
      query_string = "";
      if ((query = this.query) != null) {
        parts = [];
        keys = Object.keys(query).sort();
        for (_j = 0, _len1 = keys.length; _j < _len1; _j++) {
          key = keys[_j];
          schema = query[key];
          if ((string = params[key]) != null) {
            parts.push("" + (encodeURIComponent(key)) + "=" + (encodeURIComponent(string)));
          }
        }
        if (parts.length > 0) {
          query_string = "?" + (parts.join('&'));
        } else {
          query_string = "";
        }
      }
      return encodeURI(url + path) + query_string;
    };

    return Mapping;

  })();

}).call(this);
