// Generated by CoffeeScript 1.8.0
(function() {
  var parse_www_auth, www_auth_regex,
    __slice = [].slice;

  www_auth_regex = /([^\s,]+)="?([^\s,"]+)"?/;

  parse_www_auth = function(string) {
    var arrays, challenge, challenges, current, full, key, match, name, pair, pairs, params, token, tokens, value, _i, _j, _k, _len, _len1, _len2;
    arrays = [];
    current = null;
    tokens = string.split(" ");
    for (_i = 0, _len = tokens.length; _i < _len; _i++) {
      token = tokens[_i];
      if (token.indexOf("=") !== -1) {
        current.push(token);
      } else {
        current = [token];
        arrays.push(current);
      }
    }
    challenges = {};
    for (_j = 0, _len1 = arrays.length; _j < _len1; _j++) {
      challenge = arrays[_j];
      name = challenge[0], pairs = 2 <= challenge.length ? __slice.call(challenge, 1) : [];
      if (pairs.length === 0) {
        throw new Error("Invalid WWW-Authenticate header");
      }
      params = challenges[name] = {};
      for (_k = 0, _len2 = pairs.length; _k < _len2; _k++) {
        pair = pairs[_k];
        match = www_auth_regex.exec(pair);
        if (match != null) {
          full = match[0], key = match[1], value = match[2];
          params[key] = value;
        } else {
          throw new Error("Invalid WWW-Authenticate header");
        }
      }
    }
    return challenges;
  };

  module.exports = {
    parse_www_auth: parse_www_auth
  };

}).call(this);
