// Generated by CoffeeScript 1.8.0
(function() {
  var JSCK, SchemaManager,
    __slice = [].slice;

  JSCK = require("jsck");

  module.exports = SchemaManager = (function() {
    function SchemaManager() {
      var definition, definitions, name, schema, schemas, _i, _len, _ref;
      schemas = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      this.schemas = schemas;
      _ref = this.schemas;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        schema = _ref[_i];
        if ((definitions = schema.definitions) != null) {
          for (name in definitions) {
            definition = definitions[name];
            definition.id || (definition.id = "#" + name);
          }
        }
      }
      this.jsck = (function(func, args, ctor) {
        ctor.prototype = func.prototype;
        var child = new ctor, result = func.apply(child, args);
        return Object(result) === result ? result : child;
      })(JSCK.draft3, this.schemas, function(){});
      this.uris = this.jsck.references;
    }

    SchemaManager.prototype.find = function() {
      var args, _ref;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return (_ref = this.jsck).find.apply(_ref, args);
    };

    return SchemaManager;

  })();

}).call(this);
